# Github action to deploy the web-embed project to NPM

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/

      - name: Yarn Install
        run: yarn
        working-directory: web-embeds

      - name: Deploy to NPM
        run: yarn bump
        working-directory: web-embeds
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          YARN_REGISTRY: https://registry.npmjs.org/
